# Generated by Django 2.2.8 on 2020-12-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
