# Generated by Django 2.2.8 on 2020-12-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201225_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Glocery', 'Glocery'), ('Beverages', 'Beverages'), ('Other Categories', 'Other Categories')], default='Glocery', max_length=10),
        ),
    ]
