# Generated by Django 2.2.8 on 2021-04-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='items',
        ),
    ]
