# Generated by Django 2.2.8 on 2021-04-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
